### ISSUE TITLE
Specify Error Type in EyesBase

### ISSUE THREAD

**Issue by kidmillions** [applitools/Eyes.Sdk.JavaScript#17]
Hi,

I'm writing tests that are distinguishing error types when reporting results. Currently, failed tests using the Eyes SDK throw a standard JS Error.

It would be nice to take a page from Chai's (and other testing tools') book and throw an AssertionError (or a custom 'EyesError') instead.

For example, Chai.js uses an AssertionError spec: https://github.com/chaijs/assertion-error

https://github.com/applitools/Eyes.Sdk.JavaScript/blob/master/src/EyesBase.js#L736
```
        // Specifically handle the build test error
        if (results.asExpected === false) {
            return new EyesError('[EYES: TEST FAILED (Immediate failure report on mismatch)]');
        }
```

Thoughts? Happy to submit a version of this to the sdk, but want to hear whether y'all think this is a reasonable idea.

**Comment by danielputerman** [comment]
Hi, thanks for the feedback. That's a good idea, and one which is already implemented in other SDK. 
The only thing to note is that if we throw an EyesError, we need to do so for every error relating directly to some Eyes action. So we basically need to adjust any place in the relevant projects (selenium, utils, sdk, images) to return the new error type, not just the test failed/aborted. 

I'm planning on unifying the code base for all these projects soon, which will probably make it easier to do a PR for that specific issue.
