### ISSUE TITLE
Failed eyes.open TypeError : driver.controlFlow is not a function

### ISSUE THREAD

**Issue by pwsses** [applitools/Eyes.Sdk.JavaScript#67]
Hi.
I try with Selenium javascript tutorial (https://applitools.com/tutorials/selenium-javascript.html#quick-start)
But It failed and showing this message :  
"UnhandledPromiseRejectionWarning: TypeError: driver.controlFlow is not a function"

I refer selenium APIs but I can't find controlFlow function in selenium-webdriver.

My question, what is support selenium version in applitools?

my selenium-webdriver pacakge version is "selenium-webdriver": "^4.0.0-alpha.1"

How can I try applitools? 

thanks

**Comment by astappiev** [comment]
Hi,

This package is designed to be used with selenium 2 or 3.
If you want to use Selenium 4, you can use our new package
`@applitools/eyes-selenium`.

There is an example
https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-selenium/example/EyesWebExample.js

Best regards
