### ISSUE TITLE
Visual Grid Support

### ISSUE THREAD

**Issue by dmhalejr** [applitools/Eyes.Sdk.JavaScript#68]
Hello Applitools! 👋 

When is [visual grid](https://applitools.com/visualgrid) functionality going to be supported for the JS SDK? Is there a beta I can possible be added to? 

Thanks for all you do!

**Comment by astappiev** [comment]
Visual Grid will not be supported by the SDK.
It is already supported by new `@applitools/eyes-selenium` ([repository](https://github.com/applitools/Eyes.Sdk.JavaScript1)) package which uses `selenium-webdriver@4.0.0-alpha.1`
