### ISSUE TITLE
Typescript Typings are incorrect for TestResults

### ISSUE THREAD

**Issue by dylang** [applitools/Eyes.Sdk.JavaScript#73]
`TestResults` is a class with methods like `getName` and `setName`, not properties like `name`. 

https://github.com/applitools/Eyes.Sdk.JavaScript/blob/master/packages/eyes.sdk/typings/index.d.ts

Not correct:

```ts
export interface TestResults {
    name: string,
    secretToken: string,
    status: EyesBase.TestResultsStatus,
    appName: string,
    batchName: string,
    batchId: string,
    branchName: string,
    hostOS: string,
    hostApp: string,
    hostDisplaySize: RectangleSize,
    startedAt: Date,
    duration: number,
    isNew: boolean,
    isDifferent: boolean,
    isAborted: boolean,
    appUrls: {batch: string, session: string},
    apiUrls: {batch: string, session: string},
    stepsInfo: {name: string, isDifferent: boolean, hasBaselineImage: boolean, hasCurrentImage: boolean, appUrls: {step: string}, apiUrls: {baselineImage: string, currentImage: string, diffImage: string}}[],
    steps: number,
    matches: number,
    mismatches: number,
    missing: number,
    exactMatches: number,
    strictMatches: number,
    contentMatches: number,
    layoutMatches: number,
    noneMatches: number,
    url: string
}
```

Should be something like 

```ts
export interface TestResults {
    getName(): string;
	setName(name: string): string;
    ...
}
```

_Also, the `,` after each type should be `;`, but that's not causing problems yet._

**Comment by astappiev** [comment]
Hi @dylang,

Which version of eyes client (`eyes.selenium@3` or `eyes-selenium@4`) are you using?

Thanks

**Comment by dylang** [comment]
Hi @astappiev.
I'm using `@applitools/eyes-images`.

**Comment by astappiev** [comment]
In your case, you are using [`eyes-images`](https://www.npmjs.com/package/@applitools/eyes-images), which is [our new package](https://github.com/applitools/eyes.sdk.javascript1/tree/master/packages/eyes-images) and unfortunately, we don't have typings for it.

If you want to use the package from this repository (with typings included), use [`eyes.images`](https://www.npmjs.com/package/eyes.images) instead.

Eventually, in the future, we will provide typings for it as well. Please, contact [Applitools support](https://applitools.com/contact), they can prioritize this task.
