### ISSUE TITLE
TypeScript Typings incorrect - setHostingApp should be setHostApp

### ISSUE THREAD

**Issue by dylang** [applitools/Eyes.Sdk.JavaScript#74]
```ts
    /**
     * Sets the hosting application - overrides the one in the agent string.
     * @param hostingApp The hosting application.
     */
    setHostingApp(hostingApp: string): void;
```

This should be `setHostApp`.

**Comment by dylang** [comment]
The test is empty, maybe that's why so many type errors are getting through?

https://github.com/applitools/Eyes.Sdk.JavaScript/blob/master/packages/eyes.sdk/typings/eyes.sdk-tests.ts

**Comment by astappiev** [comment]
You are using the wrong package, the [package that you actually use](https://github.com/applitools/Eyes.Sdk.JavaScript/issues/73#issuecomment-494999319) don't have any typings yet.
